# Generated by Django 3.1.7 on 2021-03-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210327_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenges',
            name='user',
        ),
        migrations.AlterField(
            model_name='challenges',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
