# Generated by Django 3.1.7 on 2021-03-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210328_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='user',
            field=models.TextField(default='', max_length=10),
        ),
    ]
