# Generated by Django 3.1.7 on 2021-03-27 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210327_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='challenge',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.challenges'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
