# Generated by Django 3.1.7 on 2021-03-28 04:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_profile_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenges',
            old_name='created_at',
            new_name='date_posted',
        ),
        migrations.RenameField(
            model_name='challenges',
            old_name='textbox',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='status',
            name='challenge',
        ),
        migrations.AddField(
            model_name='challenges',
            name='proposer',
            field=models.TextField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='challenges',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challenges',
            name='title',
            field=models.TextField(default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='user',
            field=models.TextField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
